"use client";
import {useState} from 'react';
import {api} from '@/lib/api';
import {useData} from '@/lib/use-data';
import type {Member} from '@/lib/types';
import {useSession} from './session';
import {Button,ErrorBox,Field,Icon,Modal} from './ui';
type Invite={id:string;email:string;expires:string;used:boolean};
export function MembersScreen(){const {user,offline}=useSession();const members=useData<Member[]>('/members',[]);const [email,setEmail]=useState('');const [url,setUrl]=useState('');const [invites,setInvites]=useState<Invite[]>([]);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [remove,setRemove]=useState<Member|null>(null);
 async function loadInvites(){setInvites(await api<Invite[]>('/invitations'));}async function act(work:()=>Promise<void>){setBusy(true);setError('');try{await work();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function invite(e:React.FormEvent){e.preventDefault();await act(async()=>{const r=await api<{url:string}>('/invitations','POST',{email});setUrl(r.url);setEmail('');await loadInvites();});}
 return <><header className="page-header"><div><h1>Membros</h1><p>Um espaço partilhado pela família.</p></div></header><ErrorBox error={error||members.error}/>{message&&<p className="success" role="status">{message}</p>}<section className="panel settings-panel"><h2>A família</h2><p className="muted">Todos os membros podem gerir os ganhos e as tarefas.</p><ul className="member-list">{members.data.map(m=><li key={m.id}><span className="avatar">{m.displayName.slice(0,1).toUpperCase()}</span><div><strong>{m.displayName}</strong><small>{m.isAdmin?'Administrador':'Membro'}{m.id===user.id?' · Você':''}</small></div>{user.isAdmin&&!m.isAdmin&&<button className="icon-button" aria-label={'Remover '+m.displayName} disabled={offline||busy} onClick={()=>setRemove(m)}><Icon name="trash"/></button>}</li>)}</ul></section>{user.isAdmin&&<section className="panel settings-panel invite-panel"><h2>Convidar um membro</h2><p className="muted">O convite é válido durante 7 dias e só pode ser utilizado uma vez, pelo email indicado.</p><form onSubmit={invite}><Field label="Email do novo membro"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} maxLength={254} required disabled={offline}/></Field><Button className="primary" disabled={offline||busy}><Icon name="plus"/>Criar convite</Button></form>{url&&<div className="invite-result"><Field label="Link do convite"><input readOnly value={url} onFocus={e=>e.target.select()}/></Field><Button onClick={()=>void act(async()=>{await navigator.clipboard.writeText(url);setMessage('Link copiado. Pode enviá-lo ao novo membro.');})}>Copiar link</Button></div>}<div className="section-heading invite-history"><h3>Convites</h3><Button disabled={offline||busy} onClick={()=>void act(loadInvites)}>Ver convites</Button></div>{invites.map(i=><div className="invitation" key={i.id}><span><strong>{i.email}</strong><small>{i.used?'Utilizado ou revogado':new Date(i.expires)<new Date()?'Expirado':'Válido até '+new Date(i.expires).toLocaleDateString('pt-PT')}</small></span>{!i.used&&new Date(i.expires)>new Date()&&<Button disabled={offline||busy} onClick={()=>void act(async()=>{await api('/invitations/'+i.id,'DELETE');await loadInvites();})}>Revogar</Button>}</div>)}</section>}{remove&&<Modal title="Remover membro" onClose={()=>setRemove(null)}><p>Remover o acesso de {remove.displayName}? O histórico partilhado será preservado.</p><ErrorBox error={error}/><div className="form-actions"><Button onClick={()=>setRemove(null)}>Cancelar</Button><Button className="danger" disabled={busy} onClick={()=>void act(async()=>{await api('/members/'+remove.id,'DELETE');setRemove(null);await members.refresh();})}>Remover acesso</Button></div></Modal>}</>;}
